title: skyhorn
url: "https://skyhorn.github.io"
baseurl: "/"

markdown: kramdown

tracking_id: #

footer: no
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/about"
 - name: "Blog"
   link: "/"
 - name: "Contact"
   link: "/contact"